#!/bin/sh -ue

# This script deploys a master or release version.
#
# See [README.md] for an explanation of this and how CI should use it.
build-bin/maven/maven_deploy
# Deploy scala 2.13 also
find . -type f -name pom.xml -exec sed -i 's/_2.12/_2.13/g' {} \;
# Use a scala version that has https://search.maven.org/search?q=g:com.typesafe.genjavadoc
build-bin/maven/maven_deploy -Dscala-library.version=2.13.3
